# Generated by Django 4.1.5 on 2023-01-08 06:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to=blog.models.get_image_url, verbose_name='Фото'),
        ),
    ]
